services:
  # Infraestrutura
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Microsserviços
  api:
    build:
      context: .
      dockerfile: src/RabbitMQStudy.API/Dockerfile
    container_name: rabbitmq-api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  email-service:
    build:
      context: . 
      dockerfile: src/RabbitMQStudy.EmailService/Dockerfile
    container_name: rabbitmq-email-service
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  inventory-service:
    build:
      context: .
      dockerfile: src/RabbitMQStudy.InventoryService/Dockerfile
    container_name: rabbitmq-inventory-service
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

volumes:
  rabbitmq_data: